import { defineConfig, fontProviders } from "astro/config";
import tailwindcss from "@tailwindcss/vite";
import sitemap from "@astrojs/sitemap";
import vercel from "@astrojs/vercel";

const CLOUDINARY_CLOUD_NAME =
  process.env.PUBLIC_CLOUDINARY_CLOUD_NAME ?? "dwfcofnrd";

export default defineConfig({
  site: "https://timbenniks.dev",
  adapter: vercel({
    // Dynamic fs reads of these paths are invisible to NFT; without this the
    // serverless function looks for /var/task/src/content/*.json and ENOENTs.
    includeFiles: ["./src/content/pages.json", "./src/content/site.json"],
  }),

  build: {
    inlineStylesheets: "always",
  },

  prefetch: {
    prefetchAll: true,
    defaultStrategy: "viewport",
  },

  image: {
    service: {
      entrypoint: "./src/image-services/cloudinary.ts",
      config: {
        cloudName: CLOUDINARY_CLOUD_NAME,
        defaultFormat: "auto",
        defaultQuality: "auto",
        fetchRemote: true,
      },
    },
    remotePatterns: [
      { protocol: "https", hostname: "res.cloudinary.com" },
      { protocol: "https", hostname: "i.ytimg.com" },
      { protocol: "https", hostname: "img.youtube.com" },
    ],
  },

  fonts: [
    {
      name: "Fraunces",
      cssVariable: "--font-fraunces",
      provider: fontProviders.google(),
      weights: [400, 500],
      styles: ["normal", "italic"],
      fallbacks: ["Iowan Old Style", "Georgia", "serif"],
    },
    {
      name: "Inter",
      cssVariable: "--font-inter",
      provider: fontProviders.google(),
      weights: [400, 500, 600],
      styles: ["normal"],
      fallbacks: ["ui-sans-serif", "system-ui", "sans-serif"],
    },
  ],

  vite: {
    plugins: [tailwindcss()],
    build: {
      rollupOptions: {
        // /pagefind/pagefind.js is generated by `pagefind --site dist` after the Astro build.
        // It doesn't exist when Vite bundles, so externalize it.
        external: [/^\/pagefind\//],
      },
    },
  },

  integrations: [
    sitemap({
      filter: (page) =>
        !/\.(md|txt|xml)$/.test(page) &&
        !page.endsWith("/search") &&
        !page.endsWith("/search/") &&
        !page.includes("/admin"),
    }),
  ],
});
