import { defineConfig, fontProviders } from "astro/config";
import tailwindcss from "@tailwindcss/vite";
import sitemap from "@astrojs/sitemap";
import vercel from "@astrojs/vercel";
import { loadEnv, type Plugin } from "vite";
import { resolve } from "node:path";
import { writingRedirectMap } from "./src/data/writing-redirects";
import { assertWritingCanonicals } from "./scripts/check-writing-canonicals.mjs";

// Astro config runs before Vite's env pipeline. Seed process.env from `.env*`
// so config reads and any server code that still uses process.env see the same
// values as import.meta.env (without overwriting real shell/CI vars).
const viteMode = process.env.NODE_ENV === "production" ? "production" : "development";
for (const [key, value] of Object.entries(loadEnv(viteMode, process.cwd(), ""))) {
  if (process.env[key] === undefined) process.env[key] = value;
}

const CLOUDINARY_CLOUD_NAME =
  process.env.PUBLIC_CLOUDINARY_CLOUD_NAME ?? "dwfcofnrd";

/**
 * `loadPage` / site chrome read JSON via `fs.readFile`, so those files are not
 * in Vite's module graph. Without this, editing or Publish-to-disk in `astro
 * dev` does not refresh the browser — HMR never fires.
 */
function reloadOnContentJson(): Plugin {
  const watched = new Set([
    resolve("src/content/pages.json"),
    resolve("src/content/site.json"),
  ]);
  return {
    name: "reload-on-content-json",
    apply: "serve",
    configureServer(server) {
      if (process.env.E2E_DISABLE_HMR) return;
      const ping = (file: string) => {
        if (!watched.has(resolve(file))) return;
        server.ws.send({ type: "full-reload", path: file });
      };
      server.watcher.on("change", ping);
      server.watcher.on("add", ping);
    },
  };
}

export default defineConfig({
  site: "https://timbenniks.dev",
  redirects: writingRedirectMap(),
  adapter: vercel({
    // Dynamic fs reads of these paths are invisible to NFT; without this the
    // serverless function looks for /var/task/src/content/*.json and ENOENTs.
    includeFiles: ["./src/content/pages.json", "./src/content/site.json"],
  }),

  build: {
    inlineStylesheets: "always",
  },

  prefetch: {
    prefetchAll: true,
    defaultStrategy: "viewport",
  },

  image: {
    service: {
      entrypoint: "./src/image-services/cloudinary.ts",
      config: {
        cloudName: CLOUDINARY_CLOUD_NAME,
        defaultFormat: "auto",
        defaultQuality: "auto",
        fetchRemote: true,
      },
    },
    remotePatterns: [
      { protocol: "https", hostname: "res.cloudinary.com" },
      { protocol: "https", hostname: "i.ytimg.com" },
      { protocol: "https", hostname: "img.youtube.com" },
    ],
  },

  fonts: [
    {
      name: "Fraunces",
      cssVariable: "--font-fraunces",
      provider: fontProviders.google(),
      weights: [400, 500],
      styles: ["normal", "italic"],
      fallbacks: ["Iowan Old Style", "Georgia", "serif"],
    },
    {
      name: "Inter",
      cssVariable: "--font-inter",
      provider: fontProviders.google(),
      weights: [400, 500, 600],
      styles: ["normal"],
      fallbacks: ["ui-sans-serif", "system-ui", "sans-serif"],
    },
  ],

  vite: {
    plugins: [tailwindcss(), reloadOnContentJson()],
    server: {
      // Playwright drives a freshly started `astro dev`. A Vite full-reload
      // fired while the server finishes warming up (font provider, content
      // sync) lands between a fill() and the click() that submits it, empties
      // the form and fails the login specs. The suite never needs live reload.
      hmr: process.env.E2E_DISABLE_HMR ? false : undefined,
    },
    build: {
      rollupOptions: {
        // /pagefind/pagefind.js is generated by `pagefind --site dist` after the Astro build.
        // It doesn't exist when Vite bundles, so externalize it.
        external: [/^\/pagefind\//],
      },
    },
  },

  integrations: [
    {
      name: "assert-writing-canonicals",
      hooks: {
        "astro:build:start": () => {
          assertWritingCanonicals();
        },
      },
    },
    sitemap({
      filter: (page) =>
        !/\.(md|txt|xml|json)$/.test(page) &&
        !page.endsWith("/search") &&
        !page.endsWith("/search/") &&
        !page.includes("/admin") &&
        !page.includes("/.well-known/"),
    }),
  ],
});
