// @ts-check
import { defineConfig, fontProviders } from "astro/config";
import tailwindcss from "@tailwindcss/vite";

import sitemap from "@astrojs/sitemap";

// https://astro.build/config
export default defineConfig({
  site: "https://timbenniks.dev",

  image: {
    remotePatterns: [{ protocol: "https", hostname: "res.cloudinary.com" }],
  },

  fonts: [
    {
      name: "Fraunces",
      cssVariable: "--font-fraunces",
      provider: fontProviders.google(),
      weights: [400, 500],
      styles: ["normal", "italic"],
      fallbacks: ["Iowan Old Style", "Georgia", "serif"],
    },
    {
      name: "Inter",
      cssVariable: "--font-inter",
      provider: fontProviders.google(),
      weights: [400, 500, 600],
      styles: ["normal"],
      fallbacks: ["ui-sans-serif", "system-ui", "sans-serif"],
    },
    {
      name: "JetBrains Mono",
      cssVariable: "--font-jetbrains",
      provider: fontProviders.google(),
      weights: [400, 500],
      styles: ["normal"],
      fallbacks: ["ui-monospace", "SF Mono", "Menlo", "monospace"],
    },
  ],

  vite: {
    plugins: [tailwindcss()],
    build: {
      rollupOptions: {
        // /pagefind/pagefind.js is generated by `pagefind --site dist` after the Astro build.
        // It doesn't exist when Vite bundles, so externalize it.
        external: [/^\/pagefind\//],
      },
    },
  },

  integrations: [sitemap()],
});