// @ts-check
import { defineConfig, fontProviders } from "astro/config";
import tailwindcss from "@tailwindcss/vite";

import sitemap from "@astrojs/sitemap";

// https://astro.build/config
export default defineConfig({
  site: "https://timbenniks.dev",

  build: {
    inlineStylesheets: "always",
  },

  prefetch: {
    prefetchAll: true,
    defaultStrategy: "viewport",
  },

  image: {
    remotePatterns: [{ protocol: "https", hostname: "res.cloudinary.com" }],
  },

  fonts: [
    {
      name: "Fraunces",
      cssVariable: "--font-fraunces",
      provider: fontProviders.google(),
      weights: [400, 500],
      styles: ["normal", "italic"],
      fallbacks: ["Iowan Old Style", "Georgia", "serif"],
    },
    {
      name: "Inter",
      cssVariable: "--font-inter",
      provider: fontProviders.google(),
      weights: [400, 500, 600],
      styles: ["normal"],
      fallbacks: ["ui-sans-serif", "system-ui", "sans-serif"],
    },
  ],

  vite: {
    plugins: [tailwindcss()],
    build: {
      rollupOptions: {
        // /pagefind/pagefind.js is generated by `pagefind --site dist` after the Astro build.
        // It doesn't exist when Vite bundles, so externalize it.
        external: [/^\/pagefind\//],
      },
    },
  },

  integrations: [
    sitemap({
      // Markdown twins, plain-text endpoints, RSS, and the search UI are not pages
      // crawlers should index — they have direct surfaces (sitemap.md, feed.xml,
      // llms.txt) or are noise.
      filter: (page) =>
        !/\.(md|txt|xml)$/.test(page) && !page.endsWith('/search') && !page.endsWith('/search/'),
    }),
  ],
});